export const aboutMeData = {
  story: {
    title: "My Entrepreneurial Journey",
    subtitle: "From Tech Enthusiast to Multi-Venture Founder",
    content: [
      {
        type: "image",
        src: "/placeholder.svg?height=400&width=400&text=Arul+Murugan+Professional+Headshot",
        alt: "Arul Murugan - Professional Headshot - Entrepreneur and Founder of multiple ventures",
        caption: "Founder & CEO of multiple ventures",
      },
      {
        type: "text",
        content: `I'm Arul Murugan, a multi-venture founder, builder, and lifelong learner with a deep passion for technology, innovation, and community development. I specialize in developing scalable, secure, and impactful solutions in artificial intelligence, cybersecurity, software engineering, e-commerce, and digital marketing through my ventures including VELANTEC, ONESTOPSG, and MrAssistant.Ai.`,
      },
      {
        type: "text",
        content: `My entrepreneurial journey began with a simple vision: to create technology solutions that solve real-world problems while building communities that foster growth and innovation. This vision has led me to found multiple ventures across different sectors, each addressing unique challenges and opportunities.`,
      },
      {
        type: "video",
        src: "dQw4w9WgXcQ",
        title: "My Entrepreneurial Philosophy",
        thumbnail: "/placeholder.svg?height=315&width=560&text=Entrepreneurial+Philosophy+Video+Thumbnail",
      },
      {
        type: "text",
        content: `I believe technology is only as powerful as the problems it solves. Through VELANTEC, I lead ventures that are scalable, secure, and socially meaningful — blending modern tech with human-centered values. Whether it's through automating voice systems with MrAssistant.Ai, building vibrant communities via GrowthLab, or digitizing culture through Aval.sg and Avan.sg, I strive to create solutions that empower people and transform industries.`,
      },
      {
        type: "image",
        src: "/placeholder.svg?height=400&width=600&text=Speaking+at+Tech+Conference",
        alt: "Arul Murugan speaking at a tech conference",
        caption: "Sharing insights at the Singapore Tech Summit 2023",
      },
      {
        type: "text",
        content: `My educational background in Cyber Security & Forensics from Murdoch University, combined with my practical experience in digital marketing at ONESTOPSG, e-commerce through Aval.sg, and technology development at VELANTEC, has given me a unique perspective on building businesses that are both innovative and secure.`,
      },
      {
        type: "text",
        content: `If you're a fellow entrepreneur, innovator, or creator, let's connect. I'm always open to collaborations, partnerships, and shared learning through platforms like GrowthLab or any of my other ventures.`,
      },
    ],
  },
  ventures: [
    {
      id: "velantec",
      name: "VELANTEC",
      description: "A cutting-edge tech firm focused on AI, cybersecurity, and software solutions.",
      image: "/images/logos/velantec-logo.png",
      link: "https://www.velantec.com",
    },
    {
      id: "onestopsg",
      name: "ONESTOPSG",
      description:
        "A full-service digital marketing agency helping businesses grow through branding, SEO, and performance marketing.",
      image: "/images/logos/onestopsg-logo.png",
      link: "https://www.onestopsg.com",
    },
    {
      id: "avalsg",
      name: "Aval.sg",
      description:
        "E-commerce platform offering authentic South Indian women's clothing to customers in Singapore and beyond.",
      image: "/images/logos/aval-logo.png",
      link: "https://www.aval.sg",
    },
    {
      id: "avansg",
      name: "Avan.sg",
      description:
        "E-commerce platform specializing in authentic South Indian men's clothing for customers in Singapore.",
      image: "/images/logos/avan-logo.png",
      link: "https://www.avan.sg",
    },
    {
      id: "growthlab",
      name: "GrowthLab",
      description: "A curated community for founders, investors, and startup professionals.",
      image: "/images/logos/growthlab-logo.png",
      link: "https://www.growthlab.sg",
    },
    {
      id: "mrassistant",
      name: "MrAssistant.Ai",
      description:
        "A revolutionary AI-powered ultra-realistic voice agent platform that replaces traditional IVR systems.",
      image: "/images/logos/mrassistant-logo.png",
      link: "https://www.mrassistant.ai",
    },
  ],
  videos: [
    {
      id: "intro-video",
      title: "Introduction to Arul Murugan",
      description: "Learn about my entrepreneurial journey and vision for the future.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=Intro+Video+Thumbnail",
      videoId: "dQw4w9WgXcQ",
      duration: "3:45",
    },
    {
      id: "velantec-demo",
      title: "VELANTEC Technology Demo",
      description: "A demonstration of our cutting-edge AI and cybersecurity solutions.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=VELANTEC+Demo+Thumbnail",
      videoId: "dQw4w9WgXcQ",
      duration: "5:20",
    },
    {
      id: "mrassistant-demo",
      title: "MrAssistant.Ai Voice Agent Demo",
      description: "See our revolutionary AI-powered voice agent in action.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=Mrassistant.ai+Demo+Thumbnail",
      videoId: "dQw4w9WgXcQ",
      duration: "4:15",
    },
    {
      id: "growthlab-event",
      title: "GrowthLab Networking Event",
      description: "Highlights from our recent founder networking event in Singapore.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=GrowthLab+Event+Thumbnail",
      videoId: "dQw4w9WgXcQ",
      duration: "6:30",
    },
    {
      id: "tech-talk",
      title: "The Future of AI in Business",
      description: "My keynote speech at the Singapore Tech Summit 2023.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=Tech+Talk+Thumbnail",
      videoId: "dQw4w9WgXcQ",
      duration: "18:45",
    },
    {
      id: "avalsg-story",
      title: "The Aval.sg Story",
      description: "How we're preserving cultural heritage through fashion technology.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=Aval.sg+Story+Thumbnail",
      videoId: "dQw4w9WgXcQ",
      duration: "7:10",
    },
  ],
  gallery: [
    {
      id: "headshot-1",
      src: "/placeholder.svg?height=600&width=400&text=Professional+Headshot",
      alt: "Professional headshot of Arul Murugan",
      caption: "Professional Portrait",
      category: "portraits",
    },
    {
      id: "speaking-1",
      src: "/placeholder.svg?height=400&width=600&text=Speaking+at+Conference",
      alt: "Arul Murugan speaking at a technology conference",
      caption: "Keynote at Singapore Tech Summit 2023",
      category: "events",
    },
    {
      id: "velantec-office",
      src: "/placeholder.svg?height=400&width=600&text=VELANTEC+Office",
      alt: "VELANTEC office in Singapore",
      caption: "VELANTEC Headquarters",
      category: "ventures",
    },
    {
      id: "team-photo",
      src: "/placeholder.svg?height=400&width=600&text=Team+Photo",
      alt: "Arul Murugan with his team members",
      caption: "The VELANTEC Team",
      category: "teams",
    },
    {
      id: "growthlab-event",
      src: "/placeholder.svg?height=400&width=600&text=GrowthLab+Event",
      alt: "GrowthLab networking event",
      caption: "GrowthLab Founder Meetup 2023",
      category: "events",
    },
    {
      id: "avalsg-products",
      src: "/placeholder.svg?height=400&width=600&text=Aval.sg+Products",
      alt: "Products from Aval.sg e-commerce platform",
      caption: "Authentic South Indian Fashion Collection",
      category: "ventures",
    },
    {
      id: "interview",
      src: "/placeholder.svg?height=400&width=600&text=Media+Interview",
      alt: "Arul Murugan being interviewed by local media",
      caption: "Interview with Channel News Asia",
      category: "media",
    },
    {
      id: "award-ceremony",
      src: "/placeholder.svg?height=400&width=600&text=Award+Ceremony",
      alt: "Arul Murugan receiving an award",
      caption: "Receiving the Young Entrepreneur Award 2023",
      category: "achievements",
    },
    {
      id: "casual-portrait",
      src: "/placeholder.svg?height=600&width=400&text=Casual+Portrait",
      alt: "Casual portrait of Arul Murugan",
      caption: "Casual Portrait",
      category: "portraits",
    },
    {
      id: "onestopsg-team",
      src: "/placeholder.svg?height=400&width=600&text=ONESTOPSG+Team",
      alt: "The ONESTOPSG marketing team",
      caption: "ONESTOPSG Marketing Team",
      category: "teams",
    },
    {
      id: "mrassistant-demo",
      src: "/placeholder.svg?height=400&width=600&text=Mrassistant.ai+Demo",
      alt: "Demonstration of Mrassistant.ai voice technology",
      caption: "Mrassistant.ai Technology Demo",
      category: "ventures",
    },
    {
      id: "networking",
      src: "/placeholder.svg?height=400&width=600&text=Networking",
      alt: "Arul Murugan networking with other entrepreneurs",
      caption: "Networking at Startup Grind Singapore",
      category: "events",
    },
  ],
  achievements: [
    {
      title: "1st Place – Project Exhibition",
      issuer: "Sri Sai Ram Polytechnic College",
      date: "2019",
      description: "Won first place in the college project exhibition for innovative technical solution.",
      image: "/placeholder.svg?height=315&width=560&text=1st+Place+Project+Exhibition",
    },
    {
      title: "2nd Place – VRP Techno-Fest",
      issuer: "Technical Fest, Tamil Nadu",
      date: "2019",
      description: "Secured second place in a state-level technical festival competition.",
      image: "/placeholder.svg?height=315&width=560&text=2nd+Place+VRP+Techno-Fest",
    },
    {
      title: "Gold Award – Inter-School Competition",
      issuer: "UG HQ, Singapore",
      date: "2015",
      description: "Received gold award in an inter-school competition organized by UG HQ, Singapore.",
      image: "/placeholder.svg?height=315&width=560&text=Gold+Award+Inter-School+Competition",
    },
    {
      title: "National Youth Achievement Award",
      issuer: "Silver Medal, Singapore",
      date: "2014",
      description: "Awarded the National Youth Achievement Silver Medal for leadership and community service.",
      image: "/placeholder.svg?height=315&width=560&text=National+Youth+Achievement+Award",
    },
    {
      title: "Certificate of Merit",
      issuer: "Project Contest, Sri Sai Ram Group of Institutions",
      date: "2018",
      description: "Recognized for outstanding project work in the institutional project contest.",
      image: "/placeholder.svg?height=315&width=560&text=Certificate+of+Merit",
    },
    {
      title: "CAMP FORGE Certificate",
      issuer: "National Cadet Corps (NCC), Singapore",
      date: "2012",
      description: "Successfully completed the CAMP FORGE training program with the National Cadet Corps.",
      image: "/placeholder.svg?height=315&width=560&text=CAMP+FORGE+Certificate",
    },
  ],
}
