export const skillsData = [
  {
    name: "Entrepreneurship",
    category: "Business",
    description: "Building and scaling multiple ventures from concept to successful operation",
    icon: "FaLightbulb",
    proficiency: 95,
  },
  {
    name: "Digital Marketing",
    category: "Marketing",
    description: "Expertise in comprehensive digital marketing strategies and campaign management",
    icon: "FaChartLine",
    proficiency: 92,
  },
  {
    name: "Community Building",
    category: "Business",
    description: "Creating and nurturing professional communities and networks",
    icon: "FaUsers",
    proficiency: 90,
  },
  {
    name: "E-commerce",
    category: "Business",
    description: "Managing online retail operations, from product sourcing to customer service",
    icon: "FaStore",
    proficiency: 88,
  },
  {
    name: "Business Strategy",
    category: "Business",
    description: "Developing effective business strategies for growth and market positioning",
    icon: "FaChessKnight",
    proficiency: 90,
  },
  {
    name: "Team Leadership",
    category: "Business",
    description: "Leading teams effectively to achieve business objectives and foster growth",
    icon: "FaUserTie",
    proficiency: 92,
  },
  {
    name: "SEO",
    category: "Marketing",
    description: "Search engine optimization techniques to improve website visibility and rankings",
    icon: "FaSearch",
    proficiency: 85,
  },
  {
    name: "Social Media Marketing",
    category: "Marketing",
    description: "Strategic social media campaign planning and execution across platforms",
    icon: "FaHashtag",
    proficiency: 88,
  },
  {
    name: "Content Marketing",
    category: "Marketing",
    description: "Creating and distributing valuable content to attract and engage target audiences",
    icon: "FaFileAlt",
    proficiency: 85,
  },
  {
    name: "Cybersecurity",
    category: "Technology",
    description: "Implementing security measures to protect systems and data from threats",
    icon: "FaShieldAlt",
    proficiency: 80,
  },
  {
    name: "AI & Voice Technology",
    category: "Technology",
    description: "Applying artificial intelligence and voice technology solutions to business problems",
    icon: "FaMicrophone",
    proficiency: 78,
  },
  {
    name: "Fashion Tech",
    category: "Industry",
    description: "Merging traditional fashion retail with modern e-commerce technology",
    icon: "FaTshirt",
    proficiency: 85,
  },
  {
    name: "Supply Chain Management",
    category: "Operations",
    description: "Overseeing the flow of goods and services from suppliers to customers",
    icon: "FaTruck",
    proficiency: 82,
  },
  {
    name: "Project Management",
    category: "Operations",
    description: "Planning, executing, and closing projects efficiently and effectively",
    icon: "FaTasks",
    proficiency: 88,
  },
  {
    name: "Customer Relationship Management",
    category: "Operations",
    description: "Building and maintaining positive relationships with customers",
    icon: "FaHandshake",
    proficiency: 90,
  },
]
